Bump rancher version from 1.18.0 -> 1.19.0 (#126)
Since updating my mac I have been getting the following trying to run
Rancher
```
Error: /Applications/Rancher
Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with
code 1
```
Heard updating fixes this
([here](https://ih-epdd.slack.com/archives/C03PCJ4CBJA/p1748539058291759)).
I got these SHAs by downloading the versions
https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.19.0
and running 
```
➜  Desktop shasum -a 256 Rancher.Desktop-1.19.0.x86_64.dmg
d0a0f06556c69bce86c10e7cc0fcc88f02c9a9fa0241ea16325d0995a03425bd  Rancher.Desktop-1.19.0.x86_64.dmg
➜  Desktop shasum -a 256 Rancher.Desktop-1.19.0.aarch64.dmg
1b5c90261bcba90afb5d1372e78f1f68487b888b5a847623ab5177eb16acf112  Rancher.Desktop-1.19.0.aarch64.dmg
➜  Desktop
```

## Testing
I tested this by running 
```
 brew install --cask Casks/ih-rancher.rb
```