CLOUD-3175: avoid using rdctl for switching to virtiofs (#92)
Turns out rancher needs to actually be running to use `rdctl` to modify
settings:
```
$ $HOME/.rd/bin/rdctl set --experimental.virtual-machine.mount.type virtiofs
Error: connection refused
```

This PR changes to updating the plist file instead to use virtiofs.