CLOUD-4466: remove openssl@1.1 dependency to prevent error (#102)
Fixes:
```
Error: openssl@1.1 has been disabled because it is not supported upstream! It will be disabled on 2024-10-24.
```

Unfortunately this is likely to make it difficult to install ruby 2.7 in
old projects, so we'll need to go into those projects and either upgrade
ruby or add special install instructions.