Bump version to 0.1.28 (#58)
Got this when trying to run `meta/bump 0.1.28`:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:ConsultingMD/homebrew-ih-public.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:ConsultingMD/homebrew-ih-public.git'
```

This PR makes a PR to bump since I can't push to master (probably a good
idea).